My_Django/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("", views.BooksModelView.as_view(), name="index"),
    path("book/", views.BookList.as_view(), name="book_list"),
    path("author/", views.AuthorList.as_view(), name="author_list"),
    path("publisher/", views.PublisherList.as_view(), name="publisher_list"),
    path("book/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("author/<int:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),
    path(
        "publisher/<int:pk>/",
        views.PublisherDetailView.as_view(),
        name="publisher_detail",
    ),
]

My_Django/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.Index.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("books/", include("books.urls")),
]

My_Django/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:pk>/results/", views.ResultView.as_view(), name="results"),
]

My_Django/books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField("Author")
    publisher = models.ForeignKey("Publisher", on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

My_Django/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text

My_Django/books/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from .models import Book, Author, Publisher

# Create your views here.


class BooksModelView(TemplateView):
    template_name = "books/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model_list"] = ["Book", "Author", "Publisher"]
        return context


class BookList(ListView):
    model = Book


class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher


class BookDetailView(DetailView):
    model = Book


class AuthorDetailView(DetailView):
    model = Author


class PublisherDetailView(DetailView):
    model = Publisher

My_Django/myproject/views.py
from typing import Any
from django.views.generic import TemplateView

from django.apps import apps


class Index(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["app_list"] = ["polls", "books"]
        dictVerbose = {}
        for app in apps.get_app_configs():  # setting에 app을 추가한 순서대로 나옴
            if "site-packages" not in app.path:
                dictVerbose[app.label] = app.verbose_name
        context["verbose_dict"] = dictVerbose
        return context

My_Django/polls/views.py
import logging

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404

from django.views import generic

from polls.models import Question, Choice


logger = logging.getLogger(__name__)


# Create your views here.


# 클래스형
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):  # 최근 질문 5개 반환
        return Question.objects.all().order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    logger.fatal("fatal")
    logger.info("info")
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

My_Django/books/templates/books/author_detail.html
{% extends 'base_books.html' %}

{% block contents %}
    <h2>{{ object.name }}</h2>
    <ul>
        <li>
            Salutation : {{ object.salutation }}
        </li>
        <li>
            Email : {{ object.email }}
        </li>
    </ul>
{% endblock contents %}

My_Django/books/templates/books/author_list.html
{% extends 'base_books.html' %}

{% block contents %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li>
                <a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a>
            </li>
            <hr>
        {% endfor %}
    </ul>
{% endblock contents %}

My_Django/books/templates/books/book_detail.html
{% extends 'base_books.html' %}

{% block contents %}
    <h2>{{ object.title }}</h2>
    <ul>
        <li>
            Authors:
            {% for author in object.authors.all %}
                {{ author }}
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </li>
        <li>
            Publisher : {{ object.publisher }}
        </li>
        <li>
            Publication date : {{ object.publication_date }}
        </li>
    </ul>
{% endblock contents %}

My_Django/books/templates/books/book_list.html
{% extends 'base_books.html' %}

{% block contents %}
<h2>Book List</h2>
<ul>
    {% for book in object_list %}
        <li>
            <a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a>
        </li>
        <hr>
    {% endfor %}
</ul>
{% endblock contents %}

My_Django/books/templates/books/index.html
{% extends 'base_books.html' %}

{% block contents %}
<h2>Book Management System</h2>
<ul>
    {% for modelname in model_list %}
        {% with "books:"|add:modelname|lower|add:"_list" as url_var %}
        <!--    books:book_list books:author_list books:publisher -->
        <li><a href="{% url url_var %}">{{ modelname }}</a></li>
        <hr>
        {% endwith %}
    {% endfor %}
</ul>
{% endblock %}

My_Django/books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}

{% block contents %}
    <h2>{{ object.name }}</h2>
    <ul>
        <li>
            Address : {{ object.address }}
        </li>
        <li>
            Website : <a href="{{object.website}}">{{ object.website }}</a>
        </li>
    </ul>
{% endblock contents %}

My_Django/books/templates/books/publisher_list.html
{% extends 'base_books.html' %}

{% block contents %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li>
                <a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a>
            </li>
            <hr>
        {% endfor %}
    </ul>
{% endblock contents %}

My_Django/polls/templates/polls/detail.html
{% extends 'base_polls.html' %}

{% block title %}Detail{% endblock title %}

{% block contents %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
                <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock contents %}

My_Django/polls/templates/polls/index.html
{% extends 'base_polls.html' %}
{% block title %}Polls Application Site{% endblock title %}
{% block contents %}
    <h2>Polls List</h2>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'polls:detail' question.id %}" >{{ question.question_text }}</a>
                    <hr>
                </li>{# 템플릿 변수 주석 #}
            {% endfor %}
        </ul>
    {% else %}
        <p>투표가 없습니다.</p>
    {% endif %}
{% endblock contents %}

My_Django/polls/templates/polls/results.html
{% extends 'base_polls.html' %}

{% block title %}Restult{% endblock title %}

{% block contents %}
    <h1>{{question.question_text}}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock contents %}

My_Django/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
</head>
<style>
    a{text-decoration:none; color: inherit;}
    body{background-color:black; color:white;}
</style>
<body>
    <div id='nav'>
        {% block nav %}
            <a href="/">Poject Home</a> |  
            <a href="/admin">Admin</a>
        {% endblock nav %}
    </div>
    <div id='contents'>
        {% block contents %}
        
        {% endblock %}
    </div>
</body>

</html>

My_Django/templates/base_books.html
{% extends 'base.html' %}

<title>{% block title %}Books Application Site{% endblock title %}</title>

{% block nav %}
    {{ block.super }} {# 부모 요소를 그대로 가져옴 #}
    {% comment %} <a href="/books">Books</a> {% endcomment %}
{% endblock nav %}

My_Django/templates/base_polls.html
{% extends 'base.html' %}

{% block title %}Polls Application Site{% endblock title %}

{% block nav %}
    {{ block.super }} |  {# 부모 요소를 그대로 가져옴 #}
    <a href="/polls">Polls</a>
{% endblock nav %}

My_Django/templates/home.html
{% extends 'base.html' %}

{% block contents %}
    <h2>Django Applications</h2>
    <ul>
        {% for key,value in verbose_dict.items %}
            {# with appname|add:':index' as url_var #}
                <li><a href="{% url key|add:':index' %}">{{ value }}</a></li>
            {# endwith #}
        {% endfor %}
    </ul>
{% endblock contents %}